Fix/#109 non number inputs are skipped for height and reach fields during onboarding on Safari
climbjios-sg/climbjios-app pull request #254
Opened 2022-12-25 11:14 UTC by nathantew14

## Describe your changes
Issue is that the `type = "number"` prop of input fields does not correctly prevent non-numbers from being entered on Safari, but also prevents the input itself from being passed to the object of values used by `react-hook-form`, as well as mutes the `onChange` method, so the invalid height and reach entries are simply skipped (and cannot otherwise be checked)

To fix this, I moved  the `handleClickDoneButton` method to the `onSubmit` method/prop of `FormProvider`, then changed the "Skip"/"Next" button to invoke the `onSubmit` method, so that the default React's form validation which happens upon submitting a form can be used for each page of the onboarding process (without actually submitting the user info to backend).

## Issue ticket number and link
#109 

## Screenshots (if appropriate):
<img width="567" alt="Screenshot 2022-12-25 at 7 10 46 PM" src="https://user-images.githubusercontent.com/40333518/209465724-f5503b64-430c-4540-b5cb-4f297f0dd273.png">

## Checklist before requesting a review

- [ ] I have performed a self-review of my code

Does not seem to affect any behaviour on Chrome, updateUser can still be submitted at the end of the onboarding form, and EditProfile seems to still work.

2022-12-30 04:52 UTC, therizhao requested changes

2022-12-30 04:52 UTC, therizhao commented on frontend/src/pages/onboarding/UsernameForm.tsx
> +      <input hidden type="text"/>
Curious why is there a hidden input here?

2022-12-30 04:54 UTC, therizhao commented on frontend/src/pages/onboarding/UsernameForm.tsx
> +      <input hidden type="text"/>
ok i saw the other pr thx

2022-12-30 04:55 UTC, therizhao commented
Hi @nathantew14  u might want to check the lock file. I think can uncommit the changes in the lock file

2022-12-30 04:55 UTC, therizhao commented
otherwise lgtm

2022-12-30 16:49 UTC, nathantew14 commented
@therizhao after much gnashing of teeth I managed to remove the commit that changed the lock file, but now neither my backend nor frontend can be started with yarn locally

2023-01-07 05:04 UTC, therizhao approved these changes
lgtm!

2023-01-07 05:04 UTC, merged

2023-01-16 07:10 UTC, therizhao commented
@all-contributors please add @nathantew14 for code